from __future__ import annotations

from datetime import date
from html import escape
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Flowable,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from ..ai.schemas import ChatAnswer, CompareAnswer, ConversationPDFRequest
from .pdf_report import (
    BLUE,
    BLUE_DARK,
    BLUE_LIGHT,
    BORDER,
    INK,
    MUTED,
    PAPER,
    _content_page,
    _font_for_locale,
    _styles,
)


def build_conversation_pdf(
    context: dict[str, Any],
    request: ConversationPDFRequest,
    generated_on: date | None = None,
) -> bytes:
    generated_on = generated_on or date.today()
    font = _font_for_locale(request.locale)
    styles = _conversation_styles(_styles(font), font)
    output = BytesIO()
    document = BaseDocTemplate(
        output,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=19 * mm,
        bottomMargin=18 * mm,
        title=_label(
            request.locale,
            "UrbanInsight AI - Conversation Export",
            "UrbanInsight AI - 对话导出",
        ),
        author="UrbanInsight AI",
    )
    frame = Frame(
        document.leftMargin,
        document.bottomMargin,
        document.width,
        document.height,
        id="conversation",
    )
    document.addPageTemplates([
        PageTemplate(
            id="conversation",
            frames=[frame],
            onPage=lambda canvas, doc: _content_page(
                canvas, doc, context["borough"]["name"], generated_on, font
            ),
        )
    ])
    document.build(_conversation_story(context, request, generated_on, styles))
    return output.getvalue()


def _conversation_styles(
    base: dict[str, ParagraphStyle], font: str
) -> dict[str, ParagraphStyle]:
    return {
        **base,
        "title": ParagraphStyle(
            "conversation_title",
            parent=base["h1"],
            fontName=font,
            fontSize=22,
            leading=28,
            textColor=INK,
            spaceAfter=2 * mm,
        ),
        "subtitle": ParagraphStyle(
            "conversation_subtitle",
            parent=base["body"],
            fontName=font,
            fontSize=10,
            leading=15,
            textColor=MUTED,
            spaceAfter=7 * mm,
        ),
        "speaker": ParagraphStyle(
            "conversation_speaker",
            parent=base["small"],
            fontName=font,
            fontSize=8,
            leading=11,
            textColor=BLUE_DARK,
        ),
        "headline": ParagraphStyle(
            "conversation_headline",
            parent=base["card_title"],
            fontName=font,
            fontSize=11,
            leading=15,
            textColor=INK,
        ),
        "h2": ParagraphStyle(
            "conversation_section",
            parent=base["h2"],
            fontName=font,
            fontSize=10.5,
            leading=14,
            spaceBefore=2 * mm,
            spaceAfter=0.8 * mm,
        ),
    }


def _conversation_story(
    context: dict[str, Any],
    request: ConversationPDFRequest,
    generated_on: date,
    styles: dict[str, ParagraphStyle],
) -> list[Flowable]:
    locale = request.locale
    borough = context["borough"]
    story: list[Flowable] = [
        Paragraph("UrbanInsight AI", styles["small"]),
        Paragraph(_label(locale, "Conversation Export", "对话导出"), styles["title"]),
        Paragraph(
            _label(
                locale,
                "A saved record of your AI-assisted urban exploration.",
                "保存你的 AI 辅助城市探索过程。",
            ),
            styles["subtitle"],
        ),
        _area_card(borough, generated_on, locale, styles),
        Spacer(1, 7 * mm),
        Paragraph(_label(locale, "Conversation", "对话"), styles["h1"]),
    ]
    for message in request.messages:
        if message.role == "user":
            story.extend(_user_message(message.content, locale, styles))
        elif isinstance(message.answer, CompareAnswer):
            story.extend(_compare_message(message.answer, locale, styles))
        elif isinstance(message.answer, ChatAnswer):
            story.extend(_chat_message(message.answer, locale, styles))
        else:
            story.extend(_legacy_assistant_message(message.content, styles))
    story.extend([
        Spacer(1, 7 * mm),
        Paragraph(
            _label(
                locale,
                "Generated by UrbanInsight AI. This export preserves the completed conversation and does not call the AI again.",
                "由 UrbanInsight AI 生成。本文件仅保存已完成的对话，导出过程不会再次调用 AI。",
            ),
            styles["small"],
        ),
    ])
    return story


def _area_card(
    borough: dict[str, Any],
    generated_on: date,
    locale: str,
    styles: dict[str, ParagraphStyle],
) -> Table:
    return _card([
        Paragraph(_label(locale, "Area", "区域"), styles["small"]),
        Paragraph(escape(str(borough["name"])), styles["headline"]),
        Paragraph(
            f"{escape(str(borough.get('region', '')))}  |  {generated_on.isoformat()}",
            styles["small"],
        ),
    ], 160 * mm, BLUE_LIGHT, BLUE)


def _user_message(
    content: str, locale: str, styles: dict[str, ParagraphStyle]
) -> list[Flowable]:
    card = _card([
        Paragraph(_label(locale, "You", "你"), styles["speaker"]),
        Paragraph(escape(content), styles["body"]),
    ], 145 * mm, colors.HexColor("#EFF6FF"), BLUE)
    card.hAlign = "RIGHT"
    return [card, Spacer(1, 3 * mm)]


def _chat_message(
    answer: ChatAnswer, locale: str, styles: dict[str, ParagraphStyle]
) -> list[Flowable]:
    content: list[Flowable] = [
        Paragraph("Urban", styles["speaker"]),
        Paragraph(escape(answer.headline), styles["headline"]),
        Paragraph(escape(answer.summary), styles["body"]),
    ]
    for point in answer.key_points:
        content.append(Paragraph(
            f"- <b>{escape(point.title)}</b>: {escape(point.detail)}",
            styles["body"],
        ))
    if answer.bottom_line:
        content.append(Paragraph(escape(answer.bottom_line), styles["card_body"]))
    if answer.limitations:
        content.append(Paragraph(escape(answer.limitations), styles["small"]))
    return [_assistant_card(content), Spacer(1, 4 * mm)]


def _compare_message(
    answer: CompareAnswer, locale: str, styles: dict[str, ParagraphStyle]
) -> list[Flowable]:
    content: list[Flowable] = [
        Paragraph("Urban", styles["speaker"]),
        Paragraph(escape(answer.headline), styles["headline"]),
        Paragraph(escape(answer.summary), styles["body"]),
    ]
    for positioning, advantages in (
        (answer.primary_positioning, answer.primary_advantages),
        (answer.comparison_positioning, answer.comparison_advantages),
    ):
        content.append(Paragraph(escape(positioning.borough_name), styles["h2"]))
        content.append(Paragraph(
            f"<b>{escape(positioning.label)}</b> - {escape(positioning.description)}",
            styles["body"],
        ))
        for advantage in advantages:
            content.append(Paragraph(
                f"- <b>{escape(advantage.dimension)}</b>: {escape(advantage.explanation)}",
                styles["body"],
            ))
    content.append(Paragraph(escape(answer.decision_note), styles["card_body"]))
    if answer.evidence:
        content.append(Paragraph(_label(locale, "Evidence", "数据依据"), styles["h2"]))
        for item in answer.evidence:
            content.append(Paragraph(
                f"- {escape(item.label)}: {escape(item.primary_value)} vs {escape(item.comparison_value)}",
                styles["body"],
            ))
    return [_assistant_card(content), Spacer(1, 4 * mm)]


def _legacy_assistant_message(
    content: str, styles: dict[str, ParagraphStyle]
) -> list[Flowable]:
    return [
        _assistant_card([
            Paragraph("Urban", styles["speaker"]),
            Paragraph(escape(content), styles["body"]),
        ]),
        Spacer(1, 4 * mm),
    ]


def _assistant_card(content: list[Flowable]) -> Table:
    return _card(content, 153 * mm, PAPER, BORDER)


def _card(
    content: list[Flowable], width: float, background: Any, border: Any
) -> Table:
    table = Table([[item] for item in content], colWidths=[width], hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), background),
        ("BOX", (0, 0), (-1, -1), 0.7, border),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 0.7 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0.7 * mm),
        ("TOPPADDING", (0, 0), (-1, 0), 3 * mm),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 3 * mm),
    ]))
    return table


def _label(locale: str, english: str, chinese: str) -> str:
    return chinese if locale == "zh-CN" else english
